### PR TITLE
Add Gecko Code handling

### PR DESCRIPTION
**Pull request by cnkeats**
This PR aims to implement various functions of interacting with Gecko Codes to cover #177
Obsoletes #201 which is out of date

<hr>

Feature List
- [x] Toggle existing codes on and off
- [x] Delete existing codes
  - Default codes can be disabled but not deleted
- [x] Add new codes
- [x] Copy codes to clipboard

<hr>

Polishing TODO
- [x] Toast on error
- [x] Inform user when code is copied
- [x] Prevent adding duplicate codes
- [x] UI improvements
  - Suggestions very welcome

### CODE REVIEW

**Review by NikhilNarayana — CHANGES_REQUESTED** [review]

**Review by vinceau — CHANGES_REQUESTED** [review]
Thanks for taking this on! Just a few more comments. I think this title is too long.

image

and I'm also not a fan of this jump in dialog size when changing tabs:
image
image

There are a few more nits, but I think if you just rebase onto the `main` branch, the lint rules and build checks should catch them.

**Comment by cnkeats** [comment]
> and I'm also not a fan of this jump in dialog size when changing tabs:

@vinceau The three of us are in agreement on this one. Nikki and I were unsure of the best way to keep a constant dialogue width and thought best to get your input. Any code suggestions for this would be appreciated - I tried my hand at setting various width settings already and never quite got what I was after.

The rest of the changes are pushed but I'll request another review after I fix the dialogue width

**Review by vinceau — CHANGES_REQUESTED** [review]
Getting there! There are too many problems with the React component I'll just fix the rest up myself after this PR is merged. Just got a few more nits for now.

**Review by vinceau — APPROVED** [review]
LGTM! Thanks for fixing those up!

**Pull request merged**
