### PR TITLE
deps: upgrade Electron to 13.1.8

### PR DESCRIPTION
**Pull request by NikhilNarayana**
This is a pretty big jump, but functionality doesn't require many fixes.

Main reasons to upgrade are:
* Launcher will run native on M1 and we still only ship a single app bundle.
* Revealing location of replays on Linux will select the file (tested on Ubuntu).

The only issue is that during dev we see a lot more `DevTools failed to load source map` warnings.

image

It would be ideal if we could fix this, but we haven't had much success. I'm making this PR in hopes that someone might poke their head in and have a solution.

### CODE REVIEW

**Comment by ryanmcgrath** [comment]
Is the source map thing the only bit blocking this?

**Comment by NikhilNarayana** [comment]
> Is the source map thing the only bit blocking this?

It is a soft block, we might just deal with it even if it is annoying.

**Comment by vinceau** [comment]
Does the sourcemap console log warnings get spammed via `electron-log`? Cuz if they do we should change that.

**Comment by vinceau** [comment]
Closed in favour of #260

**Comment by vinceau** [comment]
Closed in favour of #260

**Pull request closed without merging**
